### ISSUE TITLE
This is a writing reminder

### ISSUE THREAD

**Issue by cloudbam** [demopark/koa-docs-Zh-CN#6]
This is a command line error
`
安装:
$ nvm install 7
$ npm i koa
$ node my-koa-app.js
`
请将nvm 做一个提示小白的我 一开始使用 nvm instal 7 安装错误 清提示我再安装一个nvml

**Comment by demopark** [comment]
@Moocliu nvm是 node 版本管理工具, 如果没有多版本共存需求, 直接安装 最新版node 然后从第二个命令开始即可
