### ISSUE TITLE
刊误：发现个错别字，方便的话可以修改一下吧

### ISSUE THREAD

**Issue by dream-approaching** [demopark/koa-docs-Zh-CN#9]
在Readme.md中[上下文，请求和响应](https://github.com/demopark/koa-docs-Zh-CN/blob/master/Readme.md#%E4%B8%8A%E4%B8%8B%E6%96%87-%E8%AF%B7%E6%B1%82%E5%92%8C%E5%93%8D%E5%BA%94)这一小节的最后：

![image](https://user-images.githubusercontent.com/22695534/63424736-a748df80-c441-11e9-99ca-ff708fbba5d4.png)

此处好像应该是`ctx.response.type`

**Comment by demopark** [comment]
已修正，感谢🙏
